# Generated by Django 4.1 on 2022-08-31 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_logo_url',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='esport.team')),
            ],
        ),
    ]
